WITH SALE_SUM AS (
  SELECT BOOK_ID, SUM(SALES) AS SALES
  FROM BOOK_SALES
  WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'  -- 인덱스 친화
  GROUP BY BOOK_ID
),
BOOK_AUTHOR AS (
  SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, A.AUTHOR_NAME, B.PRICE
  FROM BOOK B
  JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
)
SELECT
  BA.AUTHOR_ID,
  BA.AUTHOR_NAME,
  BA.CATEGORY,
  SUM(SS.SALES * BA.PRICE) AS TOTAL_SALES
FROM SALE_SUM SS
JOIN BOOK_AUTHOR BA ON BA.BOOK_ID = SS.BOOK_ID
GROUP BY BA.AUTHOR_ID, BA.AUTHOR_NAME, BA.CATEGORY
ORDER BY BA.AUTHOR_ID ASC, BA.CATEGORY DESC;
