WITH MAX_FAV AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.MAX_FAVORITES AS FAVORITES
FROM REST_INFO A JOIN MAX_FAV B ON A.FAVORITES = B.MAX_FAVORITES
GROUP BY A.FOOD_TYPE
ORDER BY B.FOOD_TYPE DESC

