-- 코드를 입력하세요
WITH RENTAL_STATE AS(
    SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE('2022-10-16') BETWEEN START_DATE AND END_DATE
)


SELECT DISTINCT A.CAR_ID,
    CASE 
        WHEN AVAILABILITY IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A LEFT JOIN RENTAL_STATE B ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC